theme: jekyll-theme-minimal
title: A study of influence in decision-making mechanisms
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: example
  - title: Example
    url: example
